CREATE DATABASE Proyek_fai;
USE Proyek_fai;

CREATE TABLE `user` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  jabatan VARCHAR(100) DEFAULT NULL,
  atasan_id INT DEFAULT NULL,
  hak_akses VARCHAR(50) DEFAULT 'user',
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (atasan_id) REFERENCES `user`(id) ON DELETE SET NULL
);
DROP TABLE USER;


